# --- CONFIG STORAGE (GETRENNT) ---

# JELLYFIN CONFIG
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv
spec:
  storageClassName: "" # Leer lassen für statische Bindung
  capacity: { storage: 10Gi }
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  hostPath: { path: "/mnt/data/jellyfin/config" }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: media
spec:
  storageClassName: ""
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 10Gi } }
  volumeName: jellyfin-config-pv
---
# PLEX CONFIG
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
spec:
  storageClassName: ""
  capacity: { storage: 10Gi }
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  hostPath: { path: "/mnt/data/plex/config" }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
  namespace: media
spec:
  storageClassName: ""
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 10Gi } }
  volumeName: plex-config-pv
---
# RADARR CONFIG
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config-pv
spec:
  storageClassName: ""
  capacity: { storage: 1Gi }
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  hostPath: { path: "/mnt/data/radarr/config" }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
  namespace: media
spec:
  storageClassName: ""
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 1Gi } }
  volumeName: radarr-config-pv
---
# SONARR CONFIG
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config-pv
spec:
  storageClassName: ""
  capacity: { storage: 1Gi }
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  hostPath: { path: "/mnt/data/sonarr/config" }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pvc
  namespace: media
spec:
  storageClassName: ""
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 1Gi } }
  volumeName: sonarr-config-pv


# --- SHARED MEDIA STORAGE (GEMEINSAM) ---

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: global-media-pv
spec:
  storageClassName: ""
  capacity: { storage: 500Gi }
  accessModes: ["ReadWriteMany"] # Erlaubt Zugriff von vielen Pods gleichzeitig
  persistentVolumeReclaimPolicy: Retain
  hostPath: { path: "/mnt/data/media" }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: global-media-pvc # Ein PVC für beide Apps!
  namespace: media
spec:
  storageClassName: ""
  accessModes: ["ReadWriteMany"]
  resources: { requests: { storage: 500Gi } }
  volumeName: global-media-pv
