apiVersion: apps/v1
kind: Deployment
metadata:
  name: wger-cache
  namespace: fitness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wger-cache
  template:
    metadata:
      labels:
        app: wger-cache
    spec:
      nodeSelector:
        kubernetes.io/hostname: homeserver
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          command:
            - redis-server
            - --save
            - "60"
            - "1"
            - --loglevel
            - warning
          volumeMounts:
            - name: redis-storage
              mountPath: /data
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: wger-redis-pvc
