apiVersion: apps/v1
kind: Deployment
metadata:
  name: wger-db
  namespace: fitness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wger-db
  template:
    metadata:
      labels:
        app: wger-db
    spec:
      nodeSelector:
        kubernetes.io/hostname: homeserver
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "wger"
            - name: POSTGRES_PASSWORD
              value: "wger"
            - name: POSTGRES_DB
              value: "wger"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - wger
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: wger-postgres-pvc
