apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/janikhenz/my-homelab.git
    targetRevision: HEAD
    path: applications/media-stack/manifests/prowlarr
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
