apiVersion: v1
kind: Namespace
metadata:
  name: media

---
apiVersion: v1
kind: Namespace
metadata:
  name: fitness

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: v1
kind: Namespace
metadata:
  name: jarvis

---
apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant

---
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud

---
apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden

---
apiVersion: v1
kind: Namespace
metadata:
  name: gaming