# VAULTWARDEN DATA
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-data-pv
spec:
  storageClassName: ""
  capacity: { storage: 1Gi }
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  hostPath: { path: "/mnt/data/vaultwarden/data" }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data-pvc
  namespace: vaultwarden
spec:
  storageClassName: ""
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 1Gi } }
  volumeName: vaultwarden-data-pv
