apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  namespace: jarvis
  labels:
    app: whisper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper
  template:
    metadata:
      labels:
        app: whisper
    spec:
      nodeSelector:
        kubernetes.io/hostname: homeserver
      containers:
        - name: whisper
          image: rhasspy/wyoming-whisper:latest
          args:
            - "--model"
            - "medium"
            - "--language"
            - "de"
          ports:
            - containerPort: 10300
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 4000m
              memory: 4Gi