apiVersion: v1
kind: Service
metadata:
  name: whisper-service
  namespace: jarvis
spec:
  type: NodePort
  selector:
    app: whisper
  ports:
    - protocol: TCP
      port: 10300
      targetPort: 10300
      nodePort: 30014
