apiVersion: v1
kind: ConfigMap
metadata:
  name: librechat-config
  namespace: jarvis
data:
  librechat.yaml: |
    version: 1.3.12
    cache: true
    interface:
      modelSelect: true
      parameters: true
      presets: true
    registration:
      socialLogins: []
    endpoints:
      allowedAddresses:
        - "ollama-service:11434"
      custom:
        - name: "Ollama"
          apiKey: "ollama"
          baseURL: "http://ollama-service:11434/v1"
          models:
            default: []
            fetch: true
          titleConvo: true
          modelDisplayLabel: "Ollama"
