apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: librechat
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: "https://github.com/JanikHenz/my-homelab.git"
    targetRevision: HEAD
    path: manifests/jarvis/librechat
  destination:
    name: homelab
    namespace: jarvis
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: librechat-secrets
      jsonPointers:
        - /data
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
