apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: https://github.com/janikhenz/my-homelab.git
    targetRevision: HEAD
    path: manifests/jarvis/ollama
  destination:
    server: https://kubernetes.default.svc
    namespace: jarvis
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
