apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: piper
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: default
  source:
    repoURL: "https://github.com/JanikHenz/my-homelab.git"
    targetRevision: HEAD
    path: manifests/jarvis/piper
  destination:
    name: homelab
    namespace: jarvis
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
