apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: piper
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: default
  source:
    repoURL: https://github.com/janikhenz/my-homelab.git
    targetRevision: HEAD
    path: manifests/jarvis/piper
  destination:
    server: https://kubernetes.default.svc
    namespace: jarvis
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
